"""
Persona Manager for Haneul AI Agent
Manages multiple AI personas and routes requests to appropriate persona
"""

from typing import Dict, Any, List, Optional
from enum import Enum
from loguru import logger

from app.personas.productivity_persona import ProductivityPersona
from app.personas.fitness_persona import FitnessPersona
from app.models.schemas import PriorityAnalysis


class PersonaType(Enum):
    """Available persona types"""
    PRODUCTIVITY = "productivity"
    FITNESS = "fitness"
    AUTO = "auto"  # Auto-detect based on content


class PersonaManager:
    """Manages multiple AI personas and intelligent routing"""
    
    def __init__(self):
        """Initialize persona manager with available personas"""
        self.personas = {
            PersonaType.PRODUCTIVITY: ProductivityPersona(),
            PersonaType.FITNESS: FitnessPersona()
        }
        
        # 키워드 기반 페르소나 자동 감지
        self.persona_keywords = {
            PersonaType.FITNESS: [
                "운동", "헬스", "트레이닝", "근육", "체중", "다이어트", 
                "피트니스", "바디빌딩", "크로스핏", "스쿼트", "데드리프트",
                "벤치프레스", "유산소", "무산소", "근력", "지구력",
                "workout", "fitness", "gym", "exercise", "training"
            ],
            PersonaType.PRODUCTIVITY: [
                "업무", "일정", "계획", "목표", "프로젝트", "회의", 
                "마감", "생산성", "효율", "시간관리", "우선순위",
                "작업", "task", "todo", "deadline", "meeting", 
                "project", "productivity", "schedule"
            ]
        }
        
        logger.info(f"PersonaManager initialized with {len(self.personas)} personas")

    def detect_persona(self, content: str, context: str = "") -> PersonaType:
        """
        콘텐츠 내용을 분석하여 적합한 페르소나 자동 감지
        
        Args:
            content: 분석할 콘텐츠
            context: 추가 맥락 정보
            
        Returns:
            적합한 PersonaType
        """
        full_text = f"{content} {context}".lower()
        
        fitness_score = 0
        productivity_score = 0
        
        # 키워드 매칭 점수 계산
        for keyword in self.persona_keywords[PersonaType.FITNESS]:
            if keyword.lower() in full_text:
                fitness_score += 1
                
        for keyword in self.persona_keywords[PersonaType.PRODUCTIVITY]:
            if keyword.lower() in full_text:
                productivity_score += 1
        
        # 점수 기반 페르소나 선택
        if fitness_score > productivity_score:
            detected_persona = PersonaType.FITNESS
        elif productivity_score > fitness_score:
            detected_persona = PersonaType.PRODUCTIVITY
        else:
            # 동점이거나 둘 다 0점인 경우 기본값
            detected_persona = PersonaType.PRODUCTIVITY
            
        logger.info(f"Persona detection - Fitness: {fitness_score}, Productivity: {productivity_score}, Selected: {detected_persona.value}")
        return detected_persona

    async def analyze_priority(
        self, 
        content: str, 
        context: str = "", 
        persona_type: PersonaType = PersonaType.AUTO
    ) -> tuple[PriorityAnalysis, PersonaType]:
        """
        지정된 또는 자동 감지된 페르소나로 우선순위 분석
        
        Args:
            content: 분석할 내용
            context: 추가 맥락
            persona_type: 사용할 페르소나 타입 (AUTO면 자동 감지)
            
        Returns:
            (PriorityAnalysis, 실제_사용된_PersonaType) 튜플
        """
        # 자동 감지 모드인 경우
        if persona_type == PersonaType.AUTO:
            persona_type = self.detect_persona(content, context)
        
        # 해당 페르소나로 분석 실행
        persona = self.personas[persona_type]
        analysis = await persona.analyze_priority(content, context)
        
        logger.info(f"Priority analysis completed by {persona_type.value} persona: {analysis.total_score}/20")
        return analysis, persona_type

    async def generate_suggestion(
        self, 
        content: str, 
        context: str = "", 
        persona_type: PersonaType = PersonaType.AUTO
    ) -> tuple[str, PersonaType]:
        """
        지정된 또는 자동 감지된 페르소나로 제안 생성
        
        Args:
            content: 제안 요청 내용
            context: 추가 맥락
            persona_type: 사용할 페르소나 타입
            
        Returns:
            (생성된_제안, 실제_사용된_PersonaType) 튜플
        """
        if persona_type == PersonaType.AUTO:
            persona_type = self.detect_persona(content, context)
        
        persona = self.personas[persona_type]
        suggestion = await persona.generate_suggestion(content, context)
        
        logger.info(f"Suggestion generated by {persona_type.value} persona")
        return suggestion, persona_type

    def get_available_personas(self) -> List[Dict[str, Any]]:
        """사용 가능한 페르소나 목록 반환"""
        return [
            {
                "type": persona_type.value,
                **persona.get_persona_info()
            }
            for persona_type, persona in self.personas.items()
        ]

    def get_persona_info(self, persona_type: PersonaType) -> Dict[str, Any]:
        """특정 페르소나 정보 반환"""
        if persona_type in self.personas:
            return {
                "type": persona_type.value,
                **self.personas[persona_type].get_persona_info()
            }
        return {}

    async def switch_persona(self, persona_type: PersonaType) -> bool:
        """페르소나 전환 (향후 세션 관리용)"""
        if persona_type in self.personas:
            logger.info(f"Switched to {persona_type.value} persona")
            return True
        return False


# 전역 페르소나 매니저 인스턴스
persona_manager = PersonaManager()