// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJlsUiVo06r6aeuLcVULpgNcnytFOWPx8',
    appId: '1:681902870139:web:e1b3702c560923bf671cde',
    messagingSenderId: '681902870139',
    projectId: 'hanoa-97393',
    authDomain: 'hanoa-97393.firebaseapp.com',
    storageBucket: 'hanoa-97393.firebasestorage.app',
    measurementId: 'G-XKSBEWE5D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8XN1gDAWVEkC2FhNhEZ0Tks7RaEOr1xc',
    appId: '1:681902870139:android:4b8c9d7e2f3a1b5c671cde',
    messagingSenderId: '681902870139',
    projectId: 'hanoa-97393',
    storageBucket: 'hanoa-97393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8XN1gDAWVEkC2FhNhEZ0Tks7RaEOr1xc',
    appId: '1:681902870139:ios:4b8c9d7e2f3a1b5c671cde',
    messagingSenderId: '681902870139',
    projectId: 'hanoa-97393',
    storageBucket: 'hanoa-97393.firebasestorage.app',
    iosBundleId: 'com.hanoa.clintest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8XN1gDAWVEkC2FhNhEZ0Tks7RaEOr1xc',
    appId: '1:681902870139:macos:4b8c9d7e2f3a1b5c671cde',
    messagingSenderId: '681902870139',
    projectId: 'hanoa-97393',
    storageBucket: 'hanoa-97393.firebasestorage.app',
    iosBundleId: 'com.hanoa.clintest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJlsUiVo06r6aeuLcVULpgNcnytFOWPx8',
    appId: '1:681902870139:web:e1b3702c560923bf671cde',
    messagingSenderId: '681902870139',
    projectId: 'hanoa-97393',
    authDomain: 'hanoa-97393.firebaseapp.com',
    storageBucket: 'hanoa-97393.firebasestorage.app',
    measurementId: 'G-XKSBEWE5D7',
  );
}